= Product Support

We understand that sometimes time is of the essence, or you just need
more guidance than our manuals and examples provide. We have worked hard
to put together a series of support options to help you as promptly and
as thoroughly as you need.

*For support details, see the sections of this page:*

* link:#contact[Requesting technical support]
* link:test_cases.html[Reproducible Test cases]
* link:#bug-found[Bugs and bug reports]
* link:#support-form[Support Form]
* link:../error_reporting.html[Error Reporting]

[#contact]
== Requesting Technical Support

The quickest mechanism for requesting support is to use the
*link:../error_reporting.html[Error Reporting]* system included within
the product. Just click the *Create Report* button and submit the case
to the
*https://github.com/eclipse-windowbuilder/windowbuilder/discussions[WindowBuilder
forum]* or bug tracking system
(*https://github.com/eclipse-windowbuilder/windowbuilder/issues[GitHub >
Tools > WindowBuilder]*)..

If you are unable to use the *link:../error_reporting.html[Error
Reporting]* system, please include our link:#support-form[support form]
with the product name, version and platform with any forum support
requests. In addition, please be sure to provide the details on your
operating system and/or development environment. Your questions should
be concise and restricted to a single incident or request. If you have
any link:test_cases.html[code] which may be relevant to the problem
please include it. Example link:test_cases.html[code] that illustrates
the problem is especially welcome (and often leads to a quicker
resolution) as are debug logs generated in the event of a system
exception.

[#bug-found]
== What if I think I've found a bug?

We appreciate the help of our users in identifying bugs in our software.
Bugs are an inconvenience to all of us, but unfortunately the reality of
software development. We accept bug reports, using the form below, via
email, fax or phone. If an exception occurs within the product, you may
also use the link:../error_reporting.html[error reporting] option.

[#support-form]
== Support Form

Example Support Form

* Product name: WindowBuilder
* Edition: 1.9.x
* OS Name/Version: Windows 7
* Priority: Standard
* Eclipse Log Attached: Yes

Please submit all support requests with the following information along
with a description of the problem and your expectations, steps to
reproduce the problem, detailed error messages, your Eclipse ".log" file
(found in your <workspace>/.metadata directory), and
link:test_cases.html[code samples] as appropriate. Please include any
other technical information that you think might be helpful to us in our
efforts to resolve the problem.

Priorities are:

* Low: minor impact, resolution desired but not required
* Standard: resolution needed, but can continue working project
* High: work substantially impaired, deadline is near, etc.
* Critical: system down, deadline imminent, etc.

Format of the support form:

* Product name:
* Version:
* OS Name/Version:
* Priority: Low/Standard/High/Critical
* Eclipse Log Attached: Yes/No
