name: Request license-review

on:
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@cc8b48d63a5d78f10c8af38baf11a45d0376f46a # 1.1.0
    with:
      projectId: tools.windowbuilder
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
