name: Request license-review

on:
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@ccf3dddc093d56fb3112f9df218930d0ef5737a8 # 1.1.0
    with:
      projectId: tools.windowbuilder
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
