name: License Check

on:
  pull_request:
    paths:
      - '**.target'

jobs:
  check-dash-licenses:
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@fc245debbf3af2aa1b70644d7a4c4719ee0393d7 # 1.1.0
    with:
      projectId: tools.windowbuilder
