name: License Check

on:
  pull_request:
    paths:
      - '**.target'

jobs:
  check-dash-licenses:
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@e586bb9764b4079b2e97606b643f42d0f251d4a8 # 1.1.0
    with:
      projectId: tools.windowbuilder
