name: Request license-review

on:
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@e586bb9764b4079b2e97606b643f42d0f251d4a8 # 1.1.0
    with:
      projectId: tools.windowbuilder
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
