name: License Check

on:
  pull_request:
    paths:
      - '**.target'

jobs:
  check-dash-licenses:
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@9162b0c070f07b1593fe65ab7af494d3030bccef # 1.1.0
    with:
      projectId: tools.windowbuilder
